name: Release

on:
  create:
    tags:
      - 'v*'
      - 'commit-*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container:
      image: ubuntu:lunar
    steps:
      - uses: actions/checkout@v4
      - name: apt-get update
        id: startup
        run: |
          echo "container_name=ubuntu-lunar" >> $GITHUB_OUTPUT
          sudo sed 's/^.*deb-src /deb-src /' -i /etc/apt/sources.list
          apt-get update
          apt-get install -y sudo apt-utils wget software-properties-common
          sudo add-apt-repository ppa:apt-fast/stable
          sudo apt-get update
          sudo apt-get -y install apt-fast
      - name: install build dependency
        run: |
          sudo apt-get update
          sudo apt-get build-dep -y mozc
      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel-${{ runner.os }}-mozc-${{ steps.startup.outputs.container_name }}
          restore-keys: bazel-${{ runner.os }}-mozc-${{ steps.startup.outputs.container_name }}
      - name: Mount rustup cache
        uses: actions/cache@v4
        with:
          path: "/home/runner/.rustup"
          key: rustup-${{ runner.os }}-mozc-${{ steps.startup.outputs.container_name }}
          restore-keys: rustup-${{ runner.os }}-mozc-${{ steps.startup.outputs.container_name }}
      - name: install build tools
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential dpkg-dev make qt6ct qt6-base-dev libfcitx5-qt6-dev curl unzip git
          version: 1.0
      - name: Install bazel
        run: |
           curl -LO https://github.com/bazelbuild/bazel/releases/download/7.1.1/bazel-7.1.1-installer-linux-x86_64.sh
           bash bazel-7.1.1-installer-linux-x86_64.sh --user
      - name: Install mold linker
        uses: rui314/setup-mold@staging
        with:
          mold-version: 2.30.0
          make-default: true
      - uses: actions/checkout@v4
        with:
          ref: ubuntu-lunar
          submodules: 'recursive'
          path: source
      - name: Setup variables
        id: variables
        shell: bash
        run: |
          cd source
          TAG=${GITHUB_REF##*/}
          git fetch --prune --unshallow --tags --no-recurse-submodules --filter=tree:0
          if [[ "$TAG" =~ ^commit- ]]; then
            COMMIT=$(git log -1 ${TAG#with-commit-} --pretty=%h)
            echo $TAG
            git tag $TAG -d
            git push origin $TAG -d
            base_tag=$(git describe --tags --abbrev=0 --always ${COMMIT})
            echo $base_tag
            base_tag=${base_tag/ubuntu-lunar*/}ubuntu-lunar
            echo $base_tag
            COUNT=$(($(git rev-list --count $COMMIT)-$(git rev-list --count $base_tag)))
            if [[ $COUNT != 0 ]];then
              TAG=$base_tag-$COUNT-g$COMMIT
            else
              TAG=$base_tag
            fi
            echo "tag_name=" $TAG
            git tag $TAG
            git push origin $TAG
            echo "tag_name=${TAG}" >> $GITHUB_OUTPUT
            echo "tag_commit=$(git log -1 --pretty=%H ${TAG})" >> $GITHUB_OUTPUT
          else
            echo $TAG
            COMMIT=$(git log -1 ${TAG} --pretty=%h)
            echo $COMMIT
            echo "tag_name=$(git describe --tags --always ${COMMIT})" >> $GITHUB_OUTPUT
            echo "tag_commit=$(git log -1 --pretty=%H ${COMMIT})" >> $GITHUB_OUTPUT
          fi
      - name: variables check
        run: |
          echo "${{ steps.variables.outputs.tag_name }}"
          echo "${{ steps.variables.outputs.tag_commit }}"
      - name: Build
        shell: bash
        run: |
          export PATH=$HOME/bin:$PATH
          source ~/.bazel/bin/bazel-complete.bash
          cd source
          sed "s/^\(LDFLAGS:=.*\)/\1 -fuse-ld=mold/" debian/rules -i
          dpkg-buildpackage -b --no-sign
          cd ..
          mkdir -p release
          mv *deb mozc_* release/
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.variables.outputs.tag_name }}"
          name: "${{ steps.variables.outputs.tag_name }}"
          omitBody: true
          artifacts: 'release/*'
          token: ${{ secrets.GITHUB_TOKEN }}

