name: Release

on:
  create:
    tags:
      - 'v*'
      - 'commit-*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container:
      image: ubuntu:mantic
    steps:
      - uses: actions/checkout@v4
      - name: apt-get update
        id: startup
        run: |
          echo "container_name=ubuntu-mantic" > $GITHUB_OUTPUT
          apt-get update
          apt-get install -y sudo apt-utils wget software-properties-common
          sudo add-apt-repository ppa:apt-fast/stable
          sudo apt-get update
          sudo apt-get -y install apt-fast
      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel-${{ runner.os }}-mozc-${{ steps.startup.outputs.container_name }}
          restore-keys: bazel-${{ runner.os }}-mozc-${{ steps.startup.outputs.container_name }}
      - name: Mount rustup cache
        uses: actions/cache@v4
        with:
          path: "/home/runner/.rustup"
          key: rustup-${{ runner.os }}-mozc-${{ steps.startup.outputs.container_name }}
          restore-keys: rustup-${{ runner.os }}-mozc-${{ steps.startup.outputs.container_name }}
      - name: install build tools
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential dpkg-dev make qt6ct qt6-base-dev libfcitx5-qt6-dev curl unzip git
          version: 1.0
      - name: install build dependency
        run: |
          sudo sed 's/^.*deb-src /deb-src /' -i /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get build-dep -y mozc
      - name: Install bazel
        run: |
           curl -LO https://github.com/bazelbuild/bazel/releases/download/7.1.1/bazel-7.1.1-installer-linux-x86_64.sh
           bash bazel-7.1.1-installer-linux-x86_64.sh --user
      - name: Install mold linker
        uses: rui314/setup-mold@staging
        with:
          mold-version: 2.30.0
          make-default: true
      - uses: actions/checkout@v4
        with:
          ref: ubuntu
          submodules: 'recursive'
          path: source
      - name: Setup variables
        id: variables
        shell: bash
        run: |
          TAG=${GITHUB_REF##*/}
          if [[ "$TAG" =~ ^commit- ]]; then
            cd source
            COMMIT=${TAG#commit-}
            git fetch --prune --unshallow --tags --no-recurse-submodules --filter=tree:0
            git tag ${TAG} -d
            git push origin ${TAG} -d
            TAG=$(git describe --tags --always ${COMMIT})
            git tag $TAG
            git push origin $TAG
          fi
          echo ${TAG}
          echo "tag_name=$(git describe --tags --always ${TAG})" > $GITHUB_OUTPUT
          echo "tag_name=$(git describe --tags --always ${TAG})"
      - name: Build
        shell: bash
        run: |
          export PATH=$HOME/bin:$PATH
          source ~/.bazel/bin/bazel-complete.bash
          cd source
          sed "s/^\(LDFLAGS:=.*\)/\1 -fuse-ld=mold/" debian/rules -i
          dpkg-buildpackage -b --no-sign
          cd ..
          mkdir -p release
          mv *deb mozc_* release/
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.variables.outputs.tag_name }}
          tag: ${{ steps.variables.outputs.tag_name }}
          omitBody: true
          artifacts: 'release/*'
          token: ${{ secrets.GITHUB_TOKEN }}

